parameters:

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $env: '%kernel.environment%'

    IceMaD\LeekWarsApiBundle\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Exception,Migrations,Response,Tests,Kernel.php,LeekWarsApiBundle.php}'
